# 1) No leading blank line
add_newline = false

# 2) Entire prompt:  
#    - starts with a space  
#    - directory â†’ git branch â†’ cmd duration â†’ prompt char  
format = "$directory$git_branch$git_metrics$cmd_duration$character"

palette = 'foo'

# Define custom colors
[palettes.foo]
# Overwrite existing color
blue = '21'
# Define new color
mustard = '#ffaa00'
blu = '#ffd5d8'
skyblue = '#00aaff'

[character]
format = '$symbol'
success_symbol = '[â¯](bold green) '
error_symbol = '[â¯](bold red) '# ~/.config/starship.toml
vimcmd_symbol = '[â® ](bold mustard)'

[cmd_duration]
min_time = 500
format = '[ï‹²](dimmed yellow) [$duration ](dimmed yellow)'

[directory]
format = '[ï¡](#ffd5d8) [$path](#1fd6ff) '
truncation_length = 2
truncation_symbol = ''
home_symbol = '~'

[git_state]
format = '[\($state( $progress_current of $progress_total)\)]($style) '
cherry_pick = '[ğŸ’ PICKING](bold red)'


[git_status]
conflicted = 'ğŸ³'
ahead = 'ğŸğŸ’¨'
behind = 'ğŸ˜°'
diverged = 'ğŸ˜µ'
up_to_date = 'âœ“'
untracked = 'ğŸ¤·'
stashed = 'ğŸ“¦'
modified = 'ğŸ“'
staged = '[++\($count\)](green)'
renamed = 'ğŸ‘…'
deleted = 'ğŸ—‘'


[git_branch]
symbol = 'ğŸŒ± '
truncation_length = 4
truncation_symbol = ''
ignore_branches = ['main']


[git_metrics]
added_style = 'bold blue'
format = '[+$added]($added_style)/[-$deleted]($deleted_style) '
