[pyprland]

# Combine all plugins into a single list
plugins = [
  "scratchpads",
  "magnify"
]

# Scratchpads
[scratchpads.term]
command = "kitty --class kitty-dropterm"
class = "kitty-dropterm"
lazy = true
size = "55% 54%"
position =  "24% 5%"
focus = true

[scratchpads.whatsie]
command = "zapzap"
class = "com.rtosta.zapzap"
size = "60% 58%"
focus = true
lazy = true

[scratchpads.mixer]
command = "pavucontrol"
class = "org.pulseaudio.pavucontrol"
size = "45% 46%"
focus = true
lazy = true
position = "30% 33%"

[scratchpads.share]
command = "rquickshare"
class = "rquickshare"
size = "40% 45%"
focus = true
lazy = true

[scratchpads.cal]
command = "qalculate-gtk "
class = "qalculate-gtk"
size = "20% 46%"
focus = true
lazy = true
position = "41% 44%"


[scratchpads.mission]
command = "missioncenter"
class = "io.missioncenter.MissionCenter"
size = "46% 47%"
lazy = true
position = "28% 37%"


[scratchpads.file]
command = "dolphin"
class = "org.kde.dolphin"
size = "46% 47%"
lazy = true
position = "28% 37%"
opacity = 0.9
ontop = false
focus = true


[scratchpads.kde]
command = "kdeconnect-app"
class = "org.kde.kdeconnect.app"
size = "24% 27%"
lazy = true
position = "37% 46%"
opacity = 0.9
focus = true



[scratchpads.clock]
command = "kclock"
class = "org.kde.kclock"
size = "20% 37%"
position = "41% 51%"
lazy = true
opacity = 0.9
focus = true
