[pyprland]

# Combine all plugins into a single list
plugins = [
  "scratchpads",
  "magnify",
  "window_cycle"
]

# Scratchpads
[scratchpads.term]
animation = "fromTop"
command = "kitty --class kitty-dropterm"
class = "kitty-dropterm"
size = "60% 60%"

[scratchpads.whatsie]
animation = "fromTop"
command = "whatsie"
class = "com.ktechpit.whatsie"
size = "60% 58%"

[scratchpads.mixer]
animation = "fromBottom"
command = "pavucontrol"
class = "org.pulseaudio.pavucontrol"
size = "45% 46%"

[scratchpads.share]
animation = "fromTop"
command = "rquickshare"
class = "rquickshare"
size = "40% 45%"

[scratchpads.cal]
animation = "fromBottom"
command = "qalculate-gtk --hide-keypad"
class = "qalculate-gtk"
size = "21% 44%"

# Window Cycling
[window_cycle]
cycle_same_class = true
