[pyprland]

plugins = [
  "scratchpads",
  "magnify",
]

[scratchpads.term]
animation = "fromTop"
command = "kitty --class kitty-dropterm"
class = "kitty-dropterm"
size = "75% 60%"

[scratchpads.whatsie]
command = "whatsie"
class = "com.ktechpit.whatsie"
animation = "fromTop"
size = "60% 60%"

[scratchpads.quickshare]
command = "rquickshare"
class = "rquickshare"
animation = "fromTop"
size = "50% 45%"

[scratchpads.cal]
command = "qalculate-gtk"
class = "qalculate-gtk"
animation = "fromTop"
size = "50% 50%"



