[pyprland]

# Combine all plugins into a single list
plugins = [
  "scratchpads",
  "magnify"
]

# Scratchpads
[scratchpads.term]
animation = "fromTop"
command = "kitty --class kitty-dropterm"
class = "kitty-dropterm"
size = "60% 60%"
focus = true  

[scratchpads.whatsie]
animation = "fromTop"
command = "zapzap"
class = "com.rtosta.zapzap"
size = "60% 58%"
focus = true
lazy = true

[scratchpads.mixer]
animation = "fromBottom"
command = "pavucontrol"
class = "org.pulseaudio.pavucontrol"
size = "45% 46%"
focus = true
lazy = true
position = "30% 33%"

[scratchpads.share]
animation = "fromTop"
command = "rquickshare"
class = "rquickshare"
size = "40% 45%"
focus = true
lazy = true

[scratchpads.cal]
animation = "fromBottom"
command = "qalculate-gtk "
class = "qalculate-gtk"
size = "21% 44%"
focus = true
position = "41% 44%"


[scratchpads.mission]
command = "missioncenter"
class = "io.missioncenter.MissionCenter"
animation = "fromBottom"
size = "46% 47%"
lazy = true
position = "28% 37%"


[scratchpads.file]
command = "dolphin"
class = "org.kde.dolphin"
animation = "fromBottom"
size = "46% 47%"
lazy = false
position = "28% 37%"
opacity = 0.9
ontop = false
focus = true  


[scratchpads.kde]
command = "kdeconnect-app"
class = "org.kde.kdeconnect.app"
animation = "fromBottom"
size = "24% 27%"
lazy = false
position = "37% 46%"
opacity = 0.9
focus = true  
